 const CartActionTypes = {
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM_START:'ADD_ITEM_START',
    ADD_ITEM_SUCCESS:'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE:'ADD_ITEM_FAILURE',
    CLEAR_ITEM_START: 'CLEAR_ITEM_START',
    CLEAR_ITEM_SUCCESS: 'CLEAR_ITEM_SUCCESS',
    CLEAR_ITEM_FAILURE: 'CLEAR_ITEM_FAILURE',
    REMOVE_ITEM_START:'REMOVE_ITEM_START',
    REMOVE_ITEM_SUCCESS:'REMOVE_ITEM_SUCCESS',
    REMOVE_ITEM_FAILURE:'REMOVE_ITEM_FAILURE',
    CLEAT_CART:'CLEAT_CART'
}

export default CartActionTypes;